// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Kszu4uQRYnMw7Ijs_yOjweI6gw7IdIE',
    appId: '1:755453095615:web:5e2fe74e669c221ae2a00a',
    messagingSenderId: '755453095615',
    projectId: 'airewards-476909',
    authDomain: 'airewards-476909.firebaseapp.com',
    storageBucket: 'airewards-476909.firebasestorage.app',
    measurementId: 'G-DR5GZN0JFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm7WhS-LtqhKYdsQqIJfwYY7DBJzBOpNU',
    appId: '1:755453095615:android:e875049341392bc6e2a00a',
    messagingSenderId: '755453095615',
    projectId: 'airewards-476909',
    storageBucket: 'airewards-476909.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm7WhS-LtqhKYdsQqIJfwYY7DBJzBOpNU',
    appId: '1:755453095615:ios:YOUR_IOS_APP_ID', // Add iOS app in Firebase Console
    messagingSenderId: '755453095615',
    projectId: 'airewards-476909',
    storageBucket: 'airewards-476909.firebasestorage.app',
    iosClientId: '755453095615-c5v90iun8t5d21eujogqivqu1c0923kq.apps.googleusercontent.com',
    iosBundleId: 'com.airewards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm7WhS-LtqhKYdsQqIJfwYY7DBJzBOpNU',
    appId: '1:755453095615:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '755453095615',
    projectId: 'airewards-476909',
    storageBucket: 'airewards-476909.firebasestorage.app',
    iosClientId: '755453095615-c5v90iun8t5d21eujogqivqu1c0923kq.apps.googleusercontent.com',
    iosBundleId: 'com.airewards',
  );
}