// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Kszu4uQRYnMw7Ijs_yOjweI6gw7IdIE',
    appId: '1:755453095615:web:5e2fe74e669c221ae2a00a',
    messagingSenderId: '755453095615',
    projectId: 'airewards-476909',
    authDomain: 'airewards-476909.firebaseapp.com',
    storageBucket: 'airewards-476909.firebasestorage.app',
    measurementId: 'G-DR5GZN0JFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC94wEqJRkmj-Q9O6XfARHc4Qe18Ks9r08',
    appId: '1:439400799171:android:YOUR_ANDROID_APP_ID', // You'll need the actual Android app ID
    messagingSenderId: '439400799171',
    projectId: 'airewards-3bed2',
    storageBucket: 'airewards-3bed2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC94wEqJRkmj-Q9O6XfARHc4Qe18Ks9r08',
    appId: '1:439400799171:ios:YOUR_IOS_APP_ID', // You'll need the actual iOS app ID
    messagingSenderId: '439400799171',
    projectId: 'airewards-3bed2',
    storageBucket: 'airewards-3bed2.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID.apps.googleusercontent.com', // Needed for Google Sign-In on iOS
    iosBundleId: 'com.example.aiRewardsSystem', // Your iOS bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC94wEqJRkmj-Q9O6XfARHc4Qe18Ks9r08',
    appId: '1:439400799171:ios:YOUR_IOS_APP_ID', // Usually same as iOS
    messagingSenderId: '439400799171',
    projectId: 'airewards-3bed2',
    storageBucket: 'airewards-3bed2.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiRewardsSystem',
  );
}